server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://finpay-postgres:5432/finpay_wallet_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Cấu hình chuẩn thẳng hàng với jpa/datasource
  kafka:
    bootstrap-servers: finpay-kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer